---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv-volume
  labels:
    app: app
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/logs"
  claimRef:
    name: app-pv-claim
    namespace: default
