---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app2-pv-claim
  labels:
    app: app2
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
