apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer-clusterrole-binding
subjects:
- kind: ServiceAccount
  name: developer-serviceaccount
  namespace: default
roleRef:
  kind: ClusterRole
  name: developer-pod-pvc-creator
  apiGroup: rbac.authorization.k8s.io

